### ISSUE TITLE
Job Planner Spring Test Version

### ISSUE THREAD

**Issue by tobwiens** [ow2-proactive/parent-bom#4]
The Job Planner code is based on the `<springweb.version>4.2.5.RELEASE</springweb.version>` which needs `<springtest.version>2.5</springtest.version>` to be `<springtest.version>4.2.5.RELEASE</springtest.version>` because of the `org.springframework.test.web` packages. 

This commit: `https://github.com/ow2-proactive/parent-bom/commit/30fb82710eaf427bb9803b3aa20806fe2faa8897` applied the `<springtest.version>2.5</springtest.version>` to the spring test dependency: 

```
<dependency>
<groupId>org.springframework</groupId>
<artifactId>spring-test</artifactId>
<version>${springtest.version}</version>
</dependency>
```
Which wasn't the case before. I assume that the gradle projects chose their version implicit. 

The Job Planner fails to compile with version 2.5, and I tested and it works fine with version  4.2.5.RELEASE.

**Comment by tobwiens** [comment]
I added a PR #5 which simply upgrades the spring test version.


I am not sure if that is okay (or if it will break other projects). @ow2-proactive/developers who can advice?

**Comment by MaelAudren** [comment]
@tobwiens The spring-test dependency was added by myself when adding cloud-automation-service dependencies to the parent-bom.

**Comment by tobwiens** [comment]
Thank you for merging @MaelAudren
